# -*- coding: utf-8 -*-
"""MAJOR_proj

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCPBpKNso0AZynVGQkgyvX-ifDo_PGma

Loading of dataset which has been created
"""

import pandas as pd

users=pd.read_csv("user.csv")
feedback=pd.read_csv("feedback.csv")

users.head()

"""Execution of NLP"""

import pandas as pd

from sklearn.feature_extraction.text import (
    TfidfVectorizer
)

users = pd.read_csv("user.csv")

users["combined_text"] = (
    users["professional_summary"]
    + " "
    + users["about_me"]
)

vectorizer = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = vectorizer.fit_transform(
    users["combined_text"]
)

"""Creating Matching Engine"""

MBTI_SCORES = {
    ("INTJ","ENFP"):100,
    ("ENFP","INTJ"):100,
    ("INFJ","ENTP"):95,
    ("ENTP","INFJ"):95
}

def mbti_score(a,b):

    return MBTI_SCORES.get((a,b),60)

def location_score(a,b):

    if a==b:
        return 100

    return 50


w1=0.5
w2=0.3
w3=0.2

def compatibility(user1,user2):

    idx1 = users[
        users["user_id"]==user1
    ].index[0]

    idx2 = users[
        users["user_id"]==user2
    ].index[0]

    text_score = cosine_similarity(
        tfidf_matrix[idx1],
        tfidf_matrix[idx2]
    )[0][0]*100

    mbti = mbti_score(
        users.loc[idx1,"mbti"],
        users.loc[idx2,"mbti"]
    )

    location = location_score(
        users.loc[idx1,"location"],
        users.loc[idx2,"location"]
    )

    total = (
        w1*text_score +
        w2*mbti +
        w3*location
    )

    return round(total,2)

from sklearn.metrics.pairwise import cosine_similarity

def compatibility(user1,user2):

    idx1 = users[
        users["user_id"]==user1
    ].index[0]

    idx2 = users[
        users["user_id"]==user2
    ].index[0]

    text_score = cosine_similarity(
        tfidf_matrix[idx1],
        tfidf_matrix[idx2]
    )[0][0]*100

    mbti = mbti_score(
        users.loc[idx1,"MBTI"],
        users.loc[idx2,"MBTI"]
    )

    location = location_score(
        users.loc[idx1,"location"],
        users.loc[idx2,"location"]
    )

    total = (
        w1*text_score +
        w2*mbti +
        w3*location
    )

    return round(total,2)

def top_matches(user_id):

    scores=[]

    for uid in users["user_id"]:

        if uid!=user_id:

            score = compatibility(
                user_id,
                uid
            )

            scores.append(
                (uid,score)
            )

    scores.sort(
        key=lambda x:x[1],
        reverse=True
    )

    return scores[:5]


top_matches("X01")

from sklearn.linear_model import LinearRegression
from sklearn.metrics.pairwise import cosine_similarity

X=[]
y=[]

for _,row in feedback.iterrows():

    idx1=users[
        users["user_id"]==
        row["user_id"]
    ].index[0]

    idx2=users[
        users["user_id"]==
        row["matched_user_id"]
    ].index[0]

    text_sim=cosine_similarity(
        tfidf_matrix[idx1],
        tfidf_matrix[idx2]
    )[0][0]

    # Fixed: changed 'mbti' to 'MBTI'
    mbti=mbti_score(
        users.loc[idx1,"MBTI"],
        users.loc[idx2,"MBTI"]
    )/100

    X.append([
        text_sim,
        mbti
    ])

    y.append(
        row["action"]
    )

model=LinearRegression()

model.fit(X,y)

print("Learned Weights")

print(
    "Text Similarity:",
    model.coef_[0]
)

print(
    "MBTI:",
    model.coef_[1]
)

# Take User ID from user
user_id = input("Enter User ID: ").strip().upper()

# Check if User ID exists
if user_id in users["user_id"].values:

    print(f"\nTop Matches for {user_id}\n")

    matches = top_matches(user_id)

    for uid, score in matches:
        print(f"{uid} ---> {score}%")

else:
    print("Invalid User ID! Please enter a valid User ID.")