import pandas as pd

data = {
    "user_id" : ["X01", "X02", "X03", "X04", "X05", "X06", "X07", "X08", "X09", "X10", "X11", "X12", "X13", "X14", "X15", "X16", "X17", "X18", "X19", "X20", "X21", "X22", "X23", "X24", "X25",
                 "X26", "X27", "X28", "X29", "X30", "X31", "X32", "X33", "X34", "X35", "X36", "X37", "X38", "X39", "X40", "X41", "X42", "X43", "X44", "X45", "X46", "X47", "X48", "X49", "X50",
                 "X51", "X52", "X53", "X54", "X55", "X56", "X57", "X58", "X59", "X60", "X61", "X62", "X63", "X64", "X65", "X66", "X67", "X68", "X69", "X70", "X71", "X72", "X73", "X74", "X75",
                 "X76", "X77", "X78","X79","X80"],
    "name" : ["Aarav","Vivaan","Advik","Reyansh","Shaurya","Ayaan","Atharv",
              "Kiaan","Arin","Ishaan","Vihaan","Dhruv","Samay","Pranay","Tejas",
              "Ojas","Ambar","Tarun","Pavan","Nikhil","Prithvi","Harit","Rajat",
              "Varun","Ayan","Yuvan","Milan","Amrit","Chaitanya","Tushar","Ansh",
              "Aahan","Neeraj","Rivan","Nivaan","Manan","Ruhan","Viren","Soham","Yash",
              "Nirav","Ishir","Tanish","Shiven","Atharvan","Arjit","Suryansh","Aarnik",
              "Rishaan","Eshanay","Zavian","Ilan","Ehan","Daksh","Parvansh","Hriday","Tanveer",
              "Shivendra","Aisha","Ishani","Vedika","Ananya","Anika","Anushka","Roshni","Kanchan",
              "Damini","Swati","Amrita","Rupali","Ragini","Ankita","Arpita","Tarini","Sarla","Vasudha",
              "Kaumudi","Prisha","Priya","Pavani"],
    "age" : [40, 20, 20, 43, 28, 27, 27, 24, 43, 23,
             41, 43, 37, 22, 38, 33, 21, 20, 22, 26,
             27, 36, 39, 20, 37, 26, 42, 40, 42, 37,
             33, 27, 34, 38, 28, 45, 20, 44, 45, 25,
             42, 33, 30, 28, 24, 26, 44, 30, 23, 22,
             32, 23, 31, 31, 39, 28, 45, 21, 43, 34,
             37, 23, 32, 22, 37, 29, 40, 39, 31, 38,
             26, 42, 22, 21, 41, 27, 44, 29, 22, 27],
    "location" : ["Bangalore","Hyderabad","Chennai","Pune","Delhi","Mumbai","Gurgaon","Noida","Kolkata","Ahmedabad",
                  "Thiruvananthapuram","Kochi","Coimbatore","Indore","Jaipur","Chandigarh","Bhubaneswar","Visakhapatnam",
                  "Lucknow","Nagpur","Vadodara","Mysore","Surat","Patna","Ranchi","Guwahati","Mangalore","Nashik","Madurai",
                  "Vijayawada","Trichy","Calicut","Salem","Thane","NaviMumbai","Gwalior","Jabalpur","Raipur","Jodhpur","Udaipur",
                  "Rajkot","Bhopal","Kanpur","Varanasi","Amritsar","Jalandhar","Ludhiana","Dehradun","Jammu","Srinagar","Agra",
                  "Meerut","Faridabad","Ghaziabad","Guntur","Warangal","Kakinada","Rajahmundry","Hubli","Dharwad","Belgaum",
                  "Shimla","Solan","Mohali","Panchkula","Bhiwadi","Haridwar","Roorkee","Bareilly","Aligarh","Gorakhpur","Jhansi",
                  "Ujjain","Aurangabad","Kolhapur","Sangli","Solapur","Amravati","Nellore","Tirupati"],
    "profession" : ["Software Engineer","Data Analyst","Business Analyst","Project Manager","Product Manager",
                    "Marketing Executive","Sales Executive","HR Manager","Recruitment Specialist","Financial Analyst",
                    "Investment Banker","Accountant","Auditor","Tax Consultant","Customer Support Executive",
                    "Operations Manager","Supply Chain Analyst","Logistics Coordinator","Procurement Specialist","Quality Assurance Engineer",
                    "UI/UX Designer","Graphic Designer","Web Developer","Mobile App Developer","Cloud Engineer",
                    "Cybersecurity Analyst","Network Administrator","IT Support Specialist","Database Administrator","DevOps Engineer",
                    "Machine Learning Engineer","AI Researcher","Content Writer","Copywriter","SEO Specialist",
                    "Digital Marketing Manager","Social Media Manager","Advertising Executive","Public Relations Officer","Event Coordinator",
                    "Teacher (Private School)","Tutor","Training Specialist","Corporate Trainer","Instructional Designer",
                    "Healthcare Consultant","Medical Representative","Pharmaceutical Sales Executive","Clinical Research Associate","Biotech Analyst",
                    "Architect","Civil Engineer","Mechanical Engineer","Electrical Engineer","Chemical Engineer",
                    "Interior Designer","Fashion Designer","Retail Store Manager","Merchandiser","E-commerce Specialist",
                    "Real Estate Agent","Property Manager","Insurance Advisor","Bank Officer","Loan Consultant",
                    "Travel Consultant","Tour Operator","Hotel Manager","Chef","Restaurant Manager",
                    "Journalist","Editor","Photographer","Videographer","Film Producer",
                    "Lawyer (Corporate)","Legal Advisor","Paralegal","Compliance Officer","Risk Analyst"],
    "exp_years" : [2, 7, 14, 9, 3, 11, 18, 5, 1, 16,
                   8, 4, 12, 19, 6, 13, 10, 15, 17, 20,
                   2, 8, 5, 14, 9, 4, 17, 11, 7, 3, 16,
                   12, 1, 19, 10, 6, 15, 13, 18, 20, 4, 9,
                   2, 14, 7, 11, 16, 5, 1, 18, 8, 13, 10, 17,
                   3, 6, 12, 19, 15, 20, 2, 7, 11, 4, 9, 16,
                   14, 5, 1, 18, 8, 12, 10, 17, 3, 6, 13, 19, 15, 20, 5, 8, 13, 9, 10],
    "professional_summary" : ["Developing scalable backend systems using Python and microservices",
                              "Analyzing business data trends using SQL and Power BI",
                              "Gathering business requirements and improving operational workflows",
                              "Managing cross-functional teams and ensuring timely project delivery",
                              "Defining product strategies and coordinating feature development",
                              "Executing marketing campaigns to improve brand visibility",
                              "Building strong client relationships and achieving sales targets",
                              "Managing employee engagement and recruitment operations",
                              "Sourcing and screening candidates for technical and non-technical roles",
                              "Performing financial forecasting and investment analysis",
                              "Advising clients on mergers, acquisitions, and investment opportunities",
                              "Maintaining financial records and preparing balance sheets",
                              "Conducting internal and external financial audits",
                              "Providing tax planning and compliance advisory services",
                              "Handling customer queries and resolving technical issues efficiently",
                              "Overseeing daily operations and process optimization",
                              "Analyzing supply chain performance and inventory management",
                              "Coordinating transportation and logistics activities",
                              "Managing procurement processes and vendor negotiations",
                              "Testing software applications to ensure product quality",
                              "Designing user-friendly interfaces and improving user experience",
                              "Creating visual graphics and branding materials for digital platforms",
                              "Developing responsive websites using modern web technologies",
                              "Building mobile applications for Android and iOS platforms",
                              "Managing cloud infrastructure and deployment automation",
                              "Monitoring systems and preventing cybersecurity threats",
                              "Maintaining network infrastructure and troubleshooting connectivity issues",
                              "Providing technical support and resolving IT-related problems",
                              "Managing databases and optimizing query performance",
                              "Automating software deployment pipelines and infrastructure management",
                              "Developing machine learning models for predictive analytics",
                              "Researching artificial intelligence algorithms and deep learning models",
                              "Writing engaging content for blogs and marketing campaigns",
                              "Creating persuasive copy for advertisements and social media",
                              "Optimizing website performance using SEO strategies",
                              "Managing digital campaigns across multiple online platforms",
                              "Creating and managing social media content strategies",
                              "Planning advertising campaigns to increase customer engagement",
                              "Managing corporate communication and media relations",
                              "Organizing events, conferences, and promotional activities",
                              "Teacher (Private School)","Tutor","Training Specialist","Corporate Trainer","Instructional Designer",
                              "Healthcare Consultant","Medical Representative","Pharmaceutical Sales Executive","Clinical Research Associate","Biotech Analyst",
                              "Architect","Civil Engineer","Mechanical Engineer","Electrical Engineer","Chemical Engineer",
                              "Interior Designer","Fashion Designer","Retail Store Manager","Merchandiser","E-commerce Specialist",
                              "Real Estate Agent","Property Manager","Insurance Advisor","Bank Officer","Loan Consultant",
                              "Travel Consultant","Tour Operator","Hotel Manager","Chef","Restaurant Manager",
                              "Journalist","Editor","Photographer","Videographer","Film Producer",
                              "Lawyer (Corporate)","Legal Advisor","Paralegal","Compliance Officer","Risk Analyst"],
    "about_me" : [  "Passionate about continuous learning and personal growth",
                    "Technology enthusiast who enjoys solving real-world problems",
                    "Creative thinker with a love for innovation and teamwork",
                    "Always curious about new ideas and emerging trends",
                    "Dedicated professional who values collaboration and integrity",
                    "Driven by challenges and opportunities to learn new skills",
                    "Enjoy exploring technology, business, and personal development",
                    "Strong believer in lifelong learning and self-improvement",
                    "Motivated individual with a passion for achieving goals",
                    "Enjoy connecting with people and sharing knowledge",
                    "Focused on building meaningful relationships and experiences",
                    "Adaptable and open-minded with a positive outlook on life",
                    "Passionate about creating value through innovation and creativity",
                    "Enjoy working in diverse environments and learning from others",
                    "Committed to excellence in both personal and professional life",
                    "Love discovering new perspectives and solving complex challenges",
                    "Results-oriented individual with strong communication skills",
                    "Enthusiastic about technology, creativity, and collaboration",
                    "Believe in continuous growth through learning and experience",
                    "Interested in exploring new opportunities and expanding skills",
                    "Problem solver who enjoys tackling challenging situations",
                    "Passionate about teamwork, leadership, and personal development",
                    "Dedicated to making a positive impact through my work",
                    "Curious learner who enjoys exploring different fields and ideas",
                    "Value creativity, adaptability, and meaningful connections",
                    "Always seeking opportunities to grow and contribute",
                    "Enjoy collaborating with people from diverse backgrounds",
                    "Driven by innovation and a desire to make a difference",
                    "Love turning ideas into practical solutions",
                    "Positive and motivated individual with strong work ethics",
                    "Interested in technology, business, and lifelong learning",
                    "Passionate about achieving goals while helping others succeed",
                    "Enjoy balancing professional growth with personal interests",
                    "Open to new experiences and continuous self-improvement",
                    "Creative and analytical thinker who enjoys learning",
                    "Dedicated to building skills and embracing new challenges",
                    "Enjoy sharing ideas and collaborating on impactful projects",
                    "Strong advocate for innovation, learning, and growth",
                    "Passionate about creating meaningful experiences and connections",
                    "Love exploring new technologies and industry trends",
                    "Focused on personal excellence and professional success",
                    "Enjoy networking and learning from talented individuals",
                    "Committed to continuous improvement and knowledge sharing",
                    "Curious, ambitious, and always eager to learn something new",
                    "Value integrity, teamwork, and professional development",
                    "Driven to achieve success through dedication and perseverance",
                    "Passionate about innovation and making a positive contribution",
                    "Enjoy challenging myself and expanding my capabilities",
                    "Open-minded professional who values creativity and collaboration",
                    "Always striving to learn, grow, and create meaningful impact",
                    "Passionate about building meaningful connections and lifelong friendships",
                    "Enjoy exploring innovative solutions to everyday challenges",
                    "Driven by curiosity and a desire to understand how things work",
                    "Believe in the power of collaboration and shared success",
                    "Always looking for opportunities to expand my knowledge and skills",
                    "Dedicated to personal growth and professional excellence",
                    "Enjoy contributing to projects that create a positive impact",
                    "Strong communicator who values honesty and mutual respect",
                    "Motivated by challenges that encourage learning and improvement",
                    "Passionate about discovering new ideas and perspectives",
                    "Enjoy working with diverse teams and learning from others",
                    "Focused on achieving goals while maintaining a healthy balance in life",
                    "Love engaging in creative problem-solving and innovation",
                    "Committed to continuous development and lifelong education",
                    "Value meaningful conversations and genuine relationships",
                    "Enthusiastic about exploring emerging technologies and trends",
                    "Driven to make a difference through dedication and hard work",
                    "Open to new experiences that foster growth and understanding",
                    "Enjoy helping others achieve their goals and aspirations",
                    "Believe that learning is a journey that never truly ends",
                    "Passionate about turning challenges into opportunities for success",
                    "Creative individual who enjoys thinking outside the box",
                    "Dedicated to building a future through knowledge and innovation",
                    "Enjoy sharing experiences and learning from different viewpoints",
                    "Focused on creating value through teamwork and collaboration",
                    "Always eager to embrace change and adapt to new environments",
                    "Love connecting ideas, people, and opportunities",
                    "Committed to making meaningful contributions wherever possible",
                    "Enjoy pursuing excellence in both personal and professional endeavors",
                    "Driven by purpose, curiosity, and a passion for growth"],
    "MBTI" : [  "INTP","INTJ","ENTJ","ESTJ","ENTJ","ENFP","ESTP","ENFJ","ENFJ","INTJ",
                "ENTJ","ISTJ","ISTJ","ISTJ","ESFJ","ESTJ","ISTJ","ESTJ","ESTJ","ISTJ",
                "INFP","ISFP","INTP","INTP","INTJ","ISTP","ISTP","ISFJ","ISTJ","INTJ",
                "INTP","INTP","INFP","ENFP","INTJ","ENFP","ENFP","ENFP","ENFJ","ESFJ",
                "ENFJ","INFJ","ENFJ","ENFJ","INFJ","INFJ","ESFP","ESFP","ISTJ","INTJ",
                "INTJ","ISTJ","ISTJ","INTJ","INTJ","ISFP","ENFP","ESTJ","ESFP","ENTP",
                "ESFP","ESTJ","ESFJ","ISTJ","ESFJ","ENFP","ESFP","ESFJ","ISFP","ESTJ",
                "ENTP","INTJ","ISFP","ISFP","ENTJ","ENTJ","INTJ","ISTJ","ISTJ","INTJ" ],
    "intrests" :  [ "Data, Fitness, Teaching",
                    "Coding, AI, Gaming",
                    "Marketing, Travel, Business",
                    "Education, Reading, Writing",
                    "Health, Fitness, Research",
                    "Design, Art, Music",
                    "Management, Business, Leadership",
                    "Writing, Poetry, Blogging",
                    "AI, Machine Learning, Coding",
                    "HR, Communication, Events",
                    "Cybersecurity, Gaming, Tech",
                    "Art, Design, Creativity",
                    "Finance, Investing, Analytics",
                    "Healthcare, Service, Wellness",
                    "Startups, Business, Networking",
                    "Research, Science, Reading",
                    "Engineering, Robotics, Technology",
                    "Media, Travel, Writing",
                    "Cloud, DevOps, Technology",
                    "Psychology, Wellness, Reading",
                    "DevOps, Automation, Coding",
                    "Architecture, Travel, Design",
                    "Business, Analytics, Consulting",
                    "Coding, AI, Music",
                    "Law, Debate, Politics",
                    "Medicine, Health, Reading",
                    "Gaming, Coding, Animation",
                    "Fashion, Art, Photography",
                    "AI, Deep Learning, Research",
                    "Health, Service, Fitness",
                    "Construction, Planning, Engineering",
                    "Travel, Blogging, Photography",
                    "Networking, Linux, Security",
                    "Community, Service, Education",
                    "Apps, Coding, Technology",
                    "Photography, Nature, Travel",
                    "Operations, Management, Strategy",
                    "Biotech, Science, Research",
                    "Electronics, Energy, Technology",
                    "Cooking, Food, Blogging",
                    "Blockchain, Crypto, Coding",
                    "Events, Networking, Travel",
                    "Education, Research, Reading",
                    "Interior Design, Art, Creativity",
                    "Hacking, Security, Coding",
                    "Music, Singing, Creativity",
                    "Logistics, Business, Management",
                    "Animals, Healthcare, Nature",
                    "Robotics, AI, Engineering",
                    "Art, Illustration, Design",
                    "Product Management, Strategy, Innovation",
                    "Sales, Negotiation, Networking",
                    "Recruitment, Talent Acquisition, HR",
                    "Investment Banking, Finance, Markets",
                    "Accounting, Taxation, Auditing",
                    "Customer Service, Communication, Support",
                    "Supply Chain, Logistics, Analytics",
                    "Procurement, Vendor Management, Operations",
                    "Software Testing, Quality Assurance, Automation",
                    "User Experience, Prototyping, Design",
                    "Web Development, JavaScript, Technology",
                    "Mobile Apps, Android, iOS",
                    "Cloud Computing, AWS, DevOps",
                    "Cybersecurity, Ethical Hacking, Networks",
                    "Database Management, SQL, Analytics",
                    "Machine Learning, Python, Data Science",
                    "Artificial Intelligence, Research, Innovation",
                    "Content Creation, Blogging, Storytelling",
                    "Copywriting, Advertising, Marketing",
                    "SEO, Digital Marketing, Analytics",
                    "Social Media, Branding, Content Strategy",
                    "Public Relations, Communication, Media",
                    "Training, Learning, Professional Development",
                    "Pharmaceuticals, Healthcare, Sales",
                    "Clinical Research, Biotechnology, Science",
                    "Real Estate, Property Investment, Sales",
                    "Insurance, Financial Planning, Consulting",
                    "Banking, Finance, Customer Relations",
                    "Hospitality, Travel, Customer Service",
                    "Film Making, Media Production, Creativity"],
}

# Programmatically ensure all arrays are of the same length (80)
min_len = 80
for key in data:
    data[key] = data[key][:min_len]

df = pd.DataFrame(data)
df.to_csv("user.csv")

print("CSV file created successfully")
print(df.info())
print(df)
